#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
numlockx &
xsetroot -cursor_name left_ptr &
setxkbmap -option grp:alt_shift_toggle us,ru &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/.config/bspwm/wallpapers/gentoo.png &
~/.config/polybar/launsh.sh &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#ff55ff"
bspc config normal_border_color "#f0cef0"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

export _JAVA_AWT_WM_NONREPARENTING=1 &
wmname LD3D &
