#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
setxkbmap -option grp:alt_shift_toggle us,ru &
polybar example &
picom --config ~/.config/picom/picom.conf &
#feh --bg-fill ~/.config/wallpapers/oxocarbon-evangelion.jpg &
feh --bg-fill ~/.config/wallpapers/wallpaper.jpg &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          15
bspc config focused_border_color "#f25892"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


